
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaAhorrosServiceATM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISolicitudNotaCreditoCtaAhorrosServiceATM", targetNamespace = "http://solicitudnotacreditoctaahorrosinterface.servicios.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISolicitudNotaCreditoCtaAhorrosServiceATM {


    /**
     * 
     * @param dto
     * @return
     *     returns com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorrosServiceATM.RespuestaNotaCreditoCtaAhorrosDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitudNotaCreditoCtaAhorros", targetNamespace = "http://solicitudnotacreditoctaahorrosinterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorrosServiceATM.SolicitudNotaCreditoCtaAhorros")
    @ResponseWrapper(localName = "solicitudNotaCreditoCtaAhorrosResponse", targetNamespace = "http://solicitudnotacreditoctaahorrosinterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorrosServiceATM.SolicitudNotaCreditoCtaAhorrosResponse")
    public RespuestaNotaCreditoCtaAhorrosDto solicitudNotaCreditoCtaAhorros(
        @WebParam(name = "dto", targetNamespace = "")
        SolicitudNotaCreditoCtaAhorrosDto dto)
        throws ServicioException_Exception
    ;

}
