
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaAhorrosServiceATM;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudNotaCreditoCtaAhorrosServiceATMService", targetNamespace = "http://SolicitudNotaCreditoCtaAhorros.servicios.procesadortransacciones.davivienda.com/")
public class SolicitudNotaCreditoCtaAhorrosServiceATMService
    extends Service
{

    private final static QName SOLICITUDNOTACREDITOCTAAHORROSSERVICEATMSERVICE_QNAME = new QName("http://SolicitudNotaCreditoCtaAhorros.servicios.procesadortransacciones.davivienda.com/", "SolicitudNotaCreditoCtaAhorrosServiceATMService");

    public SolicitudNotaCreditoCtaAhorrosServiceATMService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDNOTACREDITOCTAAHORROSSERVICEATMSERVICE_QNAME);
    }

    @WebEndpoint(name = "SolicitudNotaCreditoCtaAhorrosServiceATMPort")
    public ISolicitudNotaCreditoCtaAhorrosServiceATM getSolicitudNotaCreditoCtaAhorrosServiceATMPort() {
        return super.getPort(new QName("http://SolicitudNotaCreditoCtaAhorros.servicios.procesadortransacciones.davivienda.com/", "SolicitudNotaCreditoCtaAhorrosServiceATMPort"), ISolicitudNotaCreditoCtaAhorrosServiceATM.class);
    }
}
