
package com.davivienda.utilidades.ws.cliente.notaCreditoFM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INotaCreditoFMService", targetNamespace = "http://notacreditofminterface.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface INotaCreditoFMService {


    /**
     * 
     * @param dto
     * @return
     *     returns com.davivienda.sara.clientews.notaCreditoFM.RespuestaNotaCreditoFMDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarNotaCreditoFM", targetNamespace = "http://notacreditofminterface.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.notaCreditoFM.GenerarNotaCreditoFM")
    @ResponseWrapper(localName = "generarNotaCreditoFMResponse", targetNamespace = "http://notacreditofminterface.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.notaCreditoFM.GenerarNotaCreditoFMResponse")
    public RespuestaNotaCreditoFMDto generarNotaCreditoFM(
        @WebParam(name = "dto", targetNamespace = "")
        NotaCreditoFMDto dto)
        throws ServicioException_Exception
    ;

}
