
package com.davivienda.utilidades.ws.cliente.notaCredito;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankTrade07_HTTP_Service", targetNamespace = "http://www.davivienda.com/xml/NotaCredito")
public class BankTrade07HTTPService
    extends Service
{

    private final static QName BANKTRADE07HTTPSERVICE_QNAME = new QName("http://www.davivienda.com/xml/NotaCredito", "BankTrade07_HTTP_Service");

    public BankTrade07HTTPService(URL wsdlLocation) {
        super(wsdlLocation, BANKTRADE07HTTPSERVICE_QNAME);
    }
    
    @WebEndpoint(name = "BankTrade07_HTTP_Port")
    public NotaCreditoPortType getBankTrade07HTTPPort() {
        return super.getPort(new QName("http://www.davivienda.com/xml/NotaCredito", "BankTrade07_HTTP_Port"), NotaCreditoPortType.class);
    }

}
