
package com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AjusteCajerosAutomaticosService", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/")
public class AjusteCajerosAutomaticosService
    extends Service
{

    private final static QName AJUSTECAJEROSAUTOMATICOSSERVICE_QNAME = new QName("http://servicios.impl.procesadortransacciones.davivienda.com/", "AjusteCajerosAutomaticosService");

    
    public AjusteCajerosAutomaticosService(URL wsdlLocation) {
        super(wsdlLocation, AJUSTECAJEROSAUTOMATICOSSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns AjusteCajerosAutomaticos
     */
    @WebEndpoint(name = "AjusteCajerosAutomaticosPort")
    public AjusteCajerosAutomaticos getAjusteCajerosAutomaticosPort() {
        return super.getPort(new QName("http://servicios.impl.procesadortransacciones.davivienda.com/", "AjusteCajerosAutomaticosPort"), AjusteCajerosAutomaticos.class);
    }

}
