
package com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AjusteCajerosAutomaticos", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AjusteCajerosAutomaticos {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.RespAjustarSobranteCajeroDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajustarFaltanteCajero", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarFaltanteCajero")
    @ResponseWrapper(localName = "ajustarFaltanteCajeroResponse", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarFaltanteCajeroResponse")
    public RespAjustarSobranteCajeroDto ajustarFaltanteCajero(
        @WebParam(name = "parameter", targetNamespace = "")
        AjustarSobranteCajeroDto parameter)
        throws ServicioException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.RespuestaConsultaManejoEfectivoATMDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajustarProvisionCajero", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarProvisionCajero")
    @ResponseWrapper(localName = "ajustarProvisionCajeroResponse", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarProvisionCajeroResponse")
    public RespuestaConsultaManejoEfectivoATMDto ajustarProvisionCajero(
        @WebParam(name = "parameter", targetNamespace = "")
        ConsultaManejoEfectivoATMDto parameter)
        throws ServicioException_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.RespAjustarSobranteCajeroDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajustarSobranteCajero", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarSobranteCajero")
    @ResponseWrapper(localName = "ajustarSobranteCajeroResponse", targetNamespace = "http://servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.ajusteCajerosAutomaticos.AjustarSobranteCajeroResponse")
    public RespAjustarSobranteCajeroDto ajustarSobranteCajero(
        @WebParam(name = "parameter", targetNamespace = "")
        AjustarSobranteCajeroDto parameter)
        throws ServicioException_Exception
    ;

}
