
package com.davivienda.utilidades.ws.cliente.resumenIDOATM;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResumenIDOATMService", targetNamespace = "http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/")
public class ResumenIDOATMService
    extends Service
{
    private final static QName RESUMENIDOATMSERVICE_QNAME = new QName("http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/", "ResumenIDOATMService");

    public ResumenIDOATMService(URL wsdlLocation) {
        super(wsdlLocation, RESUMENIDOATMSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns ResumenIDOATM
     */
    @WebEndpoint(name = "ResumenIDOATMPort")
    public ResumenIDOATM getResumenIDOATMPort() {
        return super.getPort(new QName("http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/", "ResumenIDOATMPort"), ResumenIDOATM.class);
    }



}
