
package com.davivienda.utilidades.ws.cliente.resumenIDOATM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResumenIDOATM", targetNamespace = "http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResumenIDOATM {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.davivienda.sara.clientews.resumenIDOATM.RespuestaResumenIDOATMDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumenIDOATM", targetNamespace = "http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.resumenIDOATM.ResumenIDOATM_Type")
    @ResponseWrapper(localName = "resumenIDOATMResponse", targetNamespace = "http://ResumenIDOATM.servicios.impl.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.resumenIDOATM.ResumenIDOATMResponse")
    public RespuestaResumenIDOATMDto resumenIDOATM(
        @WebParam(name = "parameter", targetNamespace = "")
        ResumenIDOATMDto parameter)
        throws ServicioException_Exception
    ;

}
