
package com.davivienda.utilidades.ws.cliente.nDebitoCosto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Kioskos01_HTTP_Service", targetNamespace = "http://www.davivienda.com/xml/NotaDebitoCosto")
public class Kioskos01HTTPService
    extends Service
{
    
    private final static QName KIOSKOS01HTTPSERVICE_QNAME = new QName("http://www.davivienda.com/xml/NotaDebitoCosto", "Kioskos01_HTTP_Service");

    public Kioskos01HTTPService(URL wsdlLocation) {
        super(wsdlLocation, KIOSKOS01HTTPSERVICE_QNAME);
    }

    @WebEndpoint(name = "Kioskos01_HTTP_Port")
    public NotaDebitoCostoMsgSetPortType getKioskos01HTTPPort() {
        return super.getPort(new QName("http://www.davivienda.com/xml/NotaDebitoCosto", "Kioskos01_HTTP_Port"), NotaDebitoCostoMsgSetPortType.class);
    }

}
