
package com.davivienda.utilidades.ws.cliente.nDebitoCosto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotaDebitoCosto_MsgSetPortType", targetNamespace = "http://www.davivienda.com/xml/NotaDebitoCosto")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotaDebitoCostoMsgSetPortType {


    /**
     * 
     * @param notaDebitoCostoRequest
     * @return
     *     returns com.davivienda.sara.clientews.nDebitoCosto.NotaDebitoCostoResponseType
     */
    @WebMethod(operationName = "NotaDebitoCosto")
    @WebResult(name = "NotaDebitoCostoResponse", targetNamespace = "http://www.davivienda.com/xml/NotaDebitoCosto", partName = "NotaDebitoCostoResponse")
    public NotaDebitoCostoResponseType notaDebitoCosto(
        @WebParam(name = "NotaDebitoCostoRequest", targetNamespace = "http://www.davivienda.com/xml/NotaDebitoCosto", partName = "NotaDebitoCostoRequest")
        NotaDebitoCostoType notaDebitoCostoRequest);

}
