
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaCorriente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudNotaCreditoCtaCorrienteService", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteService")
public class SolicitudNotaCreditoCtaCorrienteService
    extends Service
{

    private final static QName SOLICITUDNOTACREDITOCTACORRIENTESERVICE_QNAME = new QName("http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteService", "SolicitudNotaCreditoCtaCorrienteService");

    public SolicitudNotaCreditoCtaCorrienteService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDNOTACREDITOCTACORRIENTESERVICE_QNAME);
    }

    @WebEndpoint(name = "SoliNotaCredCtaCteServiceInterfacePort")
    public SoliNotaCredCtaCteServiceInterface getSoliNotaCredCtaCteServiceInterfacePort() {
        return super.getPort(new QName("http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteService", "SoliNotaCredCtaCteServiceInterfacePort"), SoliNotaCredCtaCteServiceInterface.class);
    }
}
