
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaCorriente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoliNotaCredCtaCteServiceInterface", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoliNotaCredCtaCteServiceInterface {


    /**
     * 
     * @param solicitudNotaCreditoCtaCorrienteDto1
     * @return
     *     returns com.davivienda.sara.clientews.solicitudNotaCreditoCtaCorriente.RespuestaNotaCreditoCtaCorrienteDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "generarNotaCreditoCtaCorriente", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteServiceTypes", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaCorriente.GenerarNotaCreditoCtaCorriente")
    @ResponseWrapper(localName = "generarNotaCreditoCtaCorrienteResponse", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaCorrienteServiceTypes", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaCorriente.GenerarNotaCreditoCtaCorrienteResponse")
    public RespuestaNotaCreditoCtaCorrienteDto generarNotaCreditoCtaCorriente(
        @WebParam(name = "SolicitudNotaCreditoCtaCorrienteDto_1", targetNamespace = "")
        SolicitudNotaCreditoCtaCorrienteDto solicitudNotaCreditoCtaCorrienteDto1)
        throws ServicioException_Exception
    ;

}
