
package com.davivienda.utilidades.ws.cliente.envioTransportadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEnvioTransportadora", targetNamespace = "http://enviotransportadorainterface.servicios.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEnvioTransportadora {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.davivienda.sara.clientews.envioTransportadora.RespuestaDisminucionProvisionDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "envioTransportadora", targetNamespace = "http://enviotransportadorainterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.envioTransportadora.EnvioTransportadora")
    @ResponseWrapper(localName = "envioTransportadoraResponse", targetNamespace = "http://enviotransportadorainterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.envioTransportadora.EnvioTransportadoraResponse")
    public RespuestaDisminucionProvisionDto envioTransportadora(
        @WebParam(name = "arg0", targetNamespace = "")
        EnvioTransportadoraDto arg0)
        throws ServicioException_Exception
    ;

}
