
package com.davivienda.utilidades.ws.cliente.solicitarNotaDebitoCtaAhorros;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitarNotaDebitoCuentaAhorrosService", targetNamespace = "http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosService")
public class SolicitarNotaDebitoCuentaAhorrosService
    extends Service
{

    private final static QName SOLICITARNOTADEBITOCUENTAAHORROSSERVICE_QNAME = new QName("http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosService", "SolicitarNotaDebitoCuentaAhorrosService");

    public SolicitarNotaDebitoCuentaAhorrosService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITARNOTADEBITOCUENTAAHORROSSERVICE_QNAME);
    }

    @WebEndpoint(name = "SolicitarNotaDebitoCuentaAhorrosServiceInterfacePort")
    public SolicitarNotaDebitoCuentaAhorrosServiceInterface getSolicitarNotaDebitoCuentaAhorrosServiceInterfacePort() {
        return super.getPort(new QName("http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosService", "SolicitarNotaDebitoCuentaAhorrosServiceInterfacePort"), SolicitarNotaDebitoCuentaAhorrosServiceInterface.class);
    }

}
