
package com.davivienda.utilidades.ws.cliente.solicitarNotaDebitoCtaAhorros;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SolicitarNotaDebitoCuentaAhorrosServiceInterface", targetNamespace = "http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SolicitarNotaDebitoCuentaAhorrosServiceInterface {


    /**
     * 
     * @param solicitudNotaDebitoCuentaAhorrosDto1
     * @return
     *     returns com.davivienda.sara.clientews.solicitarNotaDebitoCtaAhorros.RespuestaNotaDebitoCuentaAhorrosDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "solicitarNotaDebitoCuentaAhorros", targetNamespace = "http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosServiceTypes", className = "com.davivienda.sara.clientews.solicitarNotaDebitoCtaAhorros.SolicitarNotaDebitoCuentaAhorros")
    @ResponseWrapper(localName = "solicitarNotaDebitoCuentaAhorrosResponse", targetNamespace = "http://servicios.davivienda.com/solicitarNotaDebitoCuentaAhorrosServiceTypes", className = "com.davivienda.sara.clientews.solicitarNotaDebitoCtaAhorros.SolicitarNotaDebitoCuentaAhorrosResponse")
    public RespuestaNotaDebitoCuentaAhorrosDto solicitarNotaDebitoCuentaAhorros(
        @WebParam(name = "SolicitudNotaDebitoCuentaAhorrosDto_1", targetNamespace = "")
        SolicitudNotaDebitoCuentaAhorrosDto solicitudNotaDebitoCuentaAhorrosDto1)
        throws ServicioException_Exception
    ;

}
