
package com.davivienda.utilidades.ws.cliente.otrosIngresosEgresos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OtrosIngresosEgresosService", targetNamespace = "http://OtrosIngresosEgresos.servicios.impl.procesadortransacciones.davivienda.com/")
public class OtrosIngresosEgresosService
    extends Service
{

    private final static QName OTROSINGRESOSEGRESOSSERVICE_QNAME = new QName("http://OtrosIngresosEgresos.servicios.impl.procesadortransacciones.davivienda.com/", "OtrosIngresosEgresosService");

    public OtrosIngresosEgresosService(URL wsdlLocation) {
        super(wsdlLocation, OTROSINGRESOSEGRESOSSERVICE_QNAME);
    }
    
    @WebEndpoint(name = "OtrosIngresosEgresosPort")
    public OtrosIngresosEgresos getOtrosIngresosEgresosPort() {
        return super.getPort(new QName("http://OtrosIngresosEgresos.servicios.impl.procesadortransacciones.davivienda.com/", "OtrosIngresosEgresosPort"), OtrosIngresosEgresos.class);
    }

}
