
package com.davivienda.utilidades.ws.cliente.solicitarNotaDebitoCuentaCorrienteServiceATM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISolictarNotaDebitoCuentaCorrienteServiceATM", targetNamespace = "http://solictarnotadebitocuentacorrienteinterface.servicios.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISolictarNotaDebitoCuentaCorrienteServiceATM {


    /**
     * 
     * @param dto
     * @return
     *     returns com.davivienda.sara.clientews.solicitarNotaDebitoCuentaCorrienteServiceATM.RespuestaNotaDebitoCuentaCorrienteDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solictarNotaDebitoCuentaCorriente", targetNamespace = "http://solictarnotadebitocuentacorrienteinterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solicitarNotaDebitoCuentaCorrienteServiceATM.SolictarNotaDebitoCuentaCorriente")
    @ResponseWrapper(localName = "solictarNotaDebitoCuentaCorrienteResponse", targetNamespace = "http://solictarnotadebitocuentacorrienteinterface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solicitarNotaDebitoCuentaCorrienteServiceATM.SolictarNotaDebitoCuentaCorrienteResponse")
    public RespuestaNotaDebitoCuentaCorrienteDto solictarNotaDebitoCuentaCorriente(
        @WebParam(name = "dto", targetNamespace = "")
        SolicitudNotaDebitoCuentaCorrienteDto dto)
        throws ServicioException_Exception
    ;

}
