
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaAhorros;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoliNotaCredCtaAhorrosServiceInterface", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoliNotaCredCtaAhorrosServiceInterface {


    /**
     * 
     * @param solicitudNotaCreditoCtaAhorrosDto1
     * @return
     *     returns com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorros.RespuestaNotaCreditoCtaAhorrosDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "generarNotaCreditoCtaAhorros", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosServiceTypes", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorros.GenerarNotaCreditoCtaAhorros")
    @ResponseWrapper(localName = "generarNotaCreditoCtaAhorrosResponse", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosServiceTypes", className = "com.davivienda.sara.clientews.solicitudNotaCreditoCtaAhorros.GenerarNotaCreditoCtaAhorrosResponse")
    public RespuestaNotaCreditoCtaAhorrosDto generarNotaCreditoCtaAhorros(
        @WebParam(name = "SolicitudNotaCreditoCtaAhorrosDto_1", targetNamespace = "")
        SolicitudNotaCreditoCtaAhorrosDto solicitudNotaCreditoCtaAhorrosDto1)
        throws ServicioException_Exception
    ;

}
