
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaAhorros;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudNotaCreditoCtaAhorrosService", targetNamespace = "http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosService")
public class SolicitudNotaCreditoCtaAhorrosService
    extends Service
{

    private final static QName SOLICITUDNOTACREDITOCTAAHORROSSERVICE_QNAME = new QName("http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosService", "SolicitudNotaCreditoCtaAhorrosService");

    public SolicitudNotaCreditoCtaAhorrosService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDNOTACREDITOCTAAHORROSSERVICE_QNAME);
    }

    @WebEndpoint(name = "SoliNotaCredCtaAhorrosServiceInterfacePort")
    public SoliNotaCredCtaAhorrosServiceInterface getSoliNotaCredCtaAhorrosServiceInterfacePort() {
        return super.getPort(new QName("http://servicios.davivienda.com/solicitudNotaCreditoCtaAhorrosService", "SoliNotaCredCtaAhorrosServiceInterfacePort"), SoliNotaCredCtaAhorrosServiceInterface.class);
    }

}
