
package com.davivienda.utilidades.ws.cliente.solicitarNotaDebitoCuentaAhorrosServiceATM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISolictarNotaDebitoCuentaAhorrosServiceATM", targetNamespace = "http://solictarnotadebitocuentaahorrosserviceinteface.servicios.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISolictarNotaDebitoCuentaAhorrosServiceATM {


    /**
     * 
     * @param dto
     * @return
     *     returns com.davivienda.sara.clientews.solictarNotaDebitoCuentaAhorrosServiceATM.RespuestaNotaDebitoCuentaAhorrosDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solictarNotaDebitoCuentaAhorros", targetNamespace = "http://solictarnotadebitocuentaahorrosserviceinteface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solictarNotaDebitoCuentaAhorrosServiceATM.SolictarNotaDebitoCuentaAhorros")
    @ResponseWrapper(localName = "solictarNotaDebitoCuentaAhorrosResponse", targetNamespace = "http://solictarnotadebitocuentaahorrosserviceinteface.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.sara.clientews.solictarNotaDebitoCuentaAhorrosServiceATM.SolictarNotaDebitoCuentaAhorrosResponse")
    public RespuestaNotaDebitoCuentaAhorrosDto solictarNotaDebitoCuentaAhorros(
        @WebParam(name = "dto", targetNamespace = "")
        SolicitudNotaDebitoCuentaAhorrosDto dto)
        throws ServicioException_Exception
    ;

}
