
package com.davivienda.utilidades.ws.cliente.solicitarNotaDebitoCuentaAhorrosServiceATM;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolictarNotaDebitoCuentaAhorrosServiceATMService", targetNamespace = "http://solictarnotadebitocuentaahorrosservice.servicios.procesadortransacciones.davivienda.com/")
public class SolictarNotaDebitoCuentaAhorrosServiceATMService
    extends Service
{

    private final static QName SOLICTARNOTADEBITOCUENTAAHORROSSERVICEATMSERVICE_QNAME = new QName("http://solictarnotadebitocuentaahorrosservice.servicios.procesadortransacciones.davivienda.com/", "SolictarNotaDebitoCuentaAhorrosServiceATMService");

    public SolictarNotaDebitoCuentaAhorrosServiceATMService(URL wsdlLocation) {
        super(wsdlLocation, SOLICTARNOTADEBITOCUENTAAHORROSSERVICEATMSERVICE_QNAME);
    }
   
    @WebEndpoint(name = "SolictarNotaDebitoCuentaAhorrosServiceATMPort")
    public ISolictarNotaDebitoCuentaAhorrosServiceATM getSolictarNotaDebitoCuentaAhorrosServiceATMPort() {
        return super.getPort(new QName("http://solictarnotadebitocuentaahorrosservice.servicios.procesadortransacciones.davivienda.com/", "SolictarNotaDebitoCuentaAhorrosServiceATMPort"), ISolictarNotaDebitoCuentaAhorrosServiceATM.class);
    }

}
