
package com.davivienda.utilidades.ws.cliente.solicitudNotaCreditoCtaCorrienteServiceATM;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudNotaCreditoCtaCorrienteServiceATMService", targetNamespace = "http://solicitudnotacreditoctacorriente.servicios.procesadortransacciones.davivienda.com/")
public class SolicitudNotaCreditoCtaCorrienteServiceATMService
    extends Service
{

    private final static QName SOLICITUDNOTACREDITOCTACORRIENTESERVICEATMSERVICE_QNAME = new QName("http://solicitudnotacreditoctacorriente.servicios.procesadortransacciones.davivienda.com/", "SolicitudNotaCreditoCtaCorrienteServiceATMService");

    public SolicitudNotaCreditoCtaCorrienteServiceATMService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDNOTACREDITOCTACORRIENTESERVICEATMSERVICE_QNAME);
    }

    @WebEndpoint(name = "SolicitudNotaCreditoCtaCorrienteServiceATMPort")
    public ISolicitudNotaCreditoCtaCorrienteServiceATM getSolicitudNotaCreditoCtaCorrienteServiceATMPort() {
        return super.getPort(new QName("http://solicitudnotacreditoctacorriente.servicios.procesadortransacciones.davivienda.com/", "SolicitudNotaCreditoCtaCorrienteServiceATMPort"), ISolicitudNotaCreditoCtaCorrienteServiceATM.class);
    }

}
