
package com.davivienda.utilidades.ws.cliente.egresosVarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EgresosVariosPortType", targetNamespace = "http://www.davivienda.com/xml/EgresosVarios")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EgresosVariosPortType {


    /**
     * 
     * @param request
     * @return
     *     returns com.davivienda.sara.clientews.egresosVarios.ResponseType
     */
    @WebMethod(operationName = "EgresosVarios")
    @WebResult(name = "Response", targetNamespace = "")
    @RequestWrapper(localName = "EgresosVarios", targetNamespace = "http://www.davivienda.com/xml/EgresosVarios", className = "com.davivienda.sara.clientews.egresosVarios.EgresosVariosType")
    @ResponseWrapper(localName = "EgresosVariosResponse", targetNamespace = "http://www.davivienda.com/xml/EgresosVarios", className = "com.davivienda.sara.clientews.egresosVarios.EgresosVariosRespType")
    public ResponseType egresosVarios(
        @WebParam(name = "Request", targetNamespace = "")
        RequestType request);

}
