
package com.davivienda.utilidades.ws.cliente.egresosVarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Operaciones09_HTTP_Service", targetNamespace = "http://www.davivienda.com/xml/EgresosVarios")
public class Operaciones09HTTPService
    extends Service
{

    private final static QName OPERACIONES09HTTPSERVICE_QNAME = new QName("http://www.davivienda.com/xml/EgresosVarios", "Operaciones09_HTTP_Service");

    public Operaciones09HTTPService(URL wsdlLocation) {
        super(wsdlLocation, OPERACIONES09HTTPSERVICE_QNAME);
    }

    @WebEndpoint(name = "Operaciones02_HTTP_Port")
    public EgresosVariosPortType getOperaciones02HTTPPort() {
        return super.getPort(new QName("http://www.davivienda.com/xml/EgresosVarios", "Operaciones02_HTTP_Port"), EgresosVariosPortType.class);
    }

}
