
package com.davivienda.utilidades.ws.cliente.autenticarUsuarioLdap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutenticarUsuarioLdapService", targetNamespace = "http://servicio.autenticacionldap.davivienda.com/")
public class AutenticarUsuarioLdapService extends Service {

    private final static QName AUTENTICARUSUARIOLDAPSERVICE_QNAME = new QName("http://servicio.autenticacionldap.davivienda.com/", "AutenticarUsuarioLdapService");

    public AutenticarUsuarioLdapService(URL wsdlLocation) {
        super(wsdlLocation, AUTENTICARUSUARIOLDAPSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns AutenticarUsuarioLdap
     */
    @WebEndpoint(name = "AutenticarUsuarioLdapPort")
    public AutenticarUsuarioLdap getAutenticarUsuarioLdapPort() {
        return super.getPort(new QName("http://servicio.autenticacionldap.davivienda.com/", "AutenticarUsuarioLdapPort"), AutenticarUsuarioLdap.class);
    }
}
