
package com.davivienda.utilidades.ws.cliente.consultaTotalesMultifuncional;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaTotalesMultifuncionalServiceService", targetNamespace = "http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/")
public class ConsultaTotalesMultifuncionalServiceService
    extends Service
{
    private final static QName CONSULTATOTALESMULTIFUNCIONALSERVICESERVICE_QNAME = new QName("http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/", "ConsultaTotalesMultifuncionalServiceService");

    public ConsultaTotalesMultifuncionalServiceService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTATOTALESMULTIFUNCIONALSERVICESERVICE_QNAME);
    }

    @WebEndpoint(name = "ConsultaTotalesMultifuncionalServicePort")
    public IConsultaTotalesMultifuncionalService getConsultaTotalesMultifuncionalServicePort() {
        return super.getPort(new QName("http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/", "ConsultaTotalesMultifuncionalServicePort"), IConsultaTotalesMultifuncionalService.class);
    }

}
