
package com.davivienda.utilidades.ws.cliente.consultaTotalesMultifuncional;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConsultaTotalesMultifuncionalService", targetNamespace = "http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConsultaTotalesMultifuncionalService {


    /**
     * 
     * @param dto
     * @return
     *     returns com.davivienda.utilidades.ws.cliente.consultaTotalesMultifuncional.RespuestaConsultaTotalesMultifuncionalDto
     * @throws ServicioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/")
    @RequestWrapper(localName = "consultarTotalesMultifuncional", targetNamespace = "http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.consultaTotalesMultifuncional.ConsultarTotalesMultifuncional")
    @ResponseWrapper(localName = "consultarTotalesMultifuncionalResponse", targetNamespace = "http://ConsultaTotalesMultifuncional.servicios.procesadortransacciones.davivienda.com/", className = "com.davivienda.utilidades.ws.cliente.consultaTotalesMultifuncional.ConsultarTotalesMultifuncionalResponse")
    public RespuestaConsultaTotalesMultifuncionalDto consultarTotalesMultifuncional(
        @WebParam(name = "dto", targetNamespace = "")
        ConsultaTotalesMultifuncionalDto dto)
        throws ServicioException_Exception
    ;

}
