
package com.davivienda.utilidades.ws.cliente.ingresosVarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Operaciones02_HTTP_Service", targetNamespace = "http://www.davivienda.com/xml/IngresosVarios")
public class Operaciones02HTTPService
    extends Service
{

    private final static QName OPERACIONES02HTTPSERVICE_QNAME = new QName("http://www.davivienda.com/xml/IngresosVarios", "Operaciones02_HTTP_Service");

    public Operaciones02HTTPService(URL wsdlLocation) {
        super(wsdlLocation, OPERACIONES02HTTPSERVICE_QNAME);
    }

    @WebEndpoint(name = "Operaciones02_HTTP_Port")
    public IngresosVariosMsgSetPortType getOperaciones02HTTPPort() {
        return super.getPort(new QName("http://www.davivienda.com/xml/IngresosVarios", "Operaciones02_HTTP_Port"), IngresosVariosMsgSetPortType.class);
    }
   
}
