
package com.davivienda.utilidades.ws.cliente.informeTotalesATM;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InformeTotalesATMService", targetNamespace = "http://InformeTotalesATM.servicios.impl.procesadortransacciones.davivienda.com/")
public class InformeTotalesATMService extends Service {
    private final static QName INFORMETOTALESATMSERVICE_QNAME = new QName("http://InformeTotalesATM.servicios.impl.procesadortransacciones.davivienda.com/", "InformeTotalesATMService");

    public InformeTotalesATMService(URL wsdlLocation) {
        super(wsdlLocation, INFORMETOTALESATMSERVICE_QNAME);
    }
    
    /**
     * 
     * @return
     *     returns InformeTotalesATM
     */
    @WebEndpoint(name = "InformeTotalesATMPort")
    public InformeTotalesATM getInformeTotalesATMPort() {
        return super.getPort(new QName("http://InformeTotalesATM.servicios.impl.procesadortransacciones.davivienda.com/", "InformeTotalesATMPort"), InformeTotalesATM.class);
    }
}
